In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

In [3]:
arr1 = np.arange(1, 11)
print(arr1)

arr2 = np.random.randint(1, 20, size=(3, 3))
print(arr2)


[ 1  2  3  4  5  6  7  8  9 10]
[[13  9  8]
 [10  7 18]
 [ 9 13 16]]


In [4]:
print("Sum:", arr1.sum())
print("Mean:", arr1.mean())
print("Max:", arr1.max())

arr_multip = arr1 * 2
print("Multiplied by 2:", arr_multip)
arr_repl = np.where(arr1 > 5, 0, arr1)
print("Replaced values:", arr_repl)


Sum: 55
Mean: 5.5
Max: 10
Multiplied by 2: [ 2  4  6  8 10 12 14 16 18 20]
Replaced values: [1 2 3 4 5 0 0 0 0 0]
